[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Cấu hình cổng nạp và monitor (Sử dụng đường dẫn ID bạn đã quét được)
;upload_port = /dev/serial/by-id/usb-1a86_USB_Single_Serial_5B5E050351-if00
;monitor_port = /dev/serial/by-id/usb-1a86_USB_Single_Serial_5B5E050351-if00
monitor_speed = 115200

; Ưu tiên cấu hình mặc định của board để ổn định
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; --- Các thư viện bạn đang dùng ---
lib_deps = 
    robtillaart/I2CKeyPad@^0.5.1
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.2
